# title of website
title: 启航者

# description of website
description: 品牌出海，从这里启航

# favicon of website
favicon: "https://weqihang.cn/wp-content/uploads/2022/02/logo-square-small-size-1.jpg"

# your website url
url: https://find.weqihang.cn
# # github profile url
# github: "https://github.com/gary0707yang"

# footer message
footer: © 2021-2022 @启航者

# template(theme) of your site, available:
# 1. webstack (http://webstack.cc)
template: webstack

# Google analytics
google_analytics: "G-6YB11E8N7S"

webstack:
  search:
    enabled: true
    default: google
    # 可选的搜索引擎
    engines:
      - google
      - bing
      - baidu
      - zhihu

content:
  categories:

    - name: 常用工具
      sites:
        - name: HSCODE 查询
          description: HS编码查询网(www.hsbianma.com)是提供进出口商品HS编码查询,商品编码查询的网站。
          url: https://www.hsbianma.com/
        - name: 外贸术语工具
          description: 遇到外贸缩写不认识？快来这里查一查
          url: http://www.choicexp.com/tool/business-terminology/index.htm
        - name: 人民币汇率中间价
          description: 外汇管理局权威数据
          url: https://www.safe.gov.cn/safe/rmbhlzjj/index.html
        - name: 中国银行外汇牌价
          description: 官方发布渠道
          url: https://www.boc.cn/sourcedb/whpj/
        - name: 17Track
          description: 全球包裹物流查询平台
          url: https://www.17track.net/zh-cn
        - name: 云港通
          description: 全球海运信息查询平台
          url: https://www.qingdao-port.net/
        - name: 谷歌趋势
          description: 搜索关键词位置和趋势信息
          url: https://trends.google.com/trends/
        - name: OEC World
          description: 世界经济观察，根据hs编码发掘世界市场变化
          url: https://oec.world/
        - name: Whatsapp 桌面端添加多个好友
          description: 直接使用电脑添加Whatsapp好友，提高沟通效率
          url: https://whatsappaddingtool.vercel.app/

    - name: 政府政策网站
      sites:
        - name: 中国海关总署
          description: 进出口，跨境海关指导
          url: http://www.customs.gov.cn/
        - name: 协定税率查询
          description: 税率查询官方指导
          url: http://fta.mofcom.gov.cn/
        - name: 各国商务信息
          description: 对外投资合作国别（地区）指南下载
          url: http://fec.mofcom.gov.cn/article/gbdqzn/#
        - name: 外贸实务查询
          description: 国家商务部官方出品，关税，政策，法规全面介绍
          url: http://wmsw.mofcom.gov.cn/wmsw/
        - name: 中国贸促会
          description: 中国国际贸易促进委员会
          url: https://www.ccpit.org/index.html#yewuzizhan
        - name: 中国国际商会
          description: 从事国际性商业活动的企业及与之相关的组织组成的全国性社会团体
          url: http://www.ccoic.cn/cms/
        - name: 中国出口信用保险公司
          description: 由国家出资设立、支持中国对外经济贸易发展与合作、具有独立法人地位的国有政策性保险公司
          url: https://www.sinosure.com.cn/


    - name: 社交平台
      sites:
        - name: Facebook
          description: 脸书
          url: https://www.facebook.com/
        - name: Instagram
          description: 开放式朋友圈
          url: https://www.instagram.com/
        - name: Whatsapp
          description: 客户通用聊天工具
          url: https://www.whatsapp.com/
        - name: Telegram
          description: 加密最安全的聊天软件
          url: https://telegram.org/
        - name: Pinterest
          description: 图片采集与发现
          url: https://www.pinterest.com/
        - name: Tiktok
          description: 抖音海外版
          url: https://www.tiktok.com/
        - name: Linkedin
          description: 职场社交，根据公司名称搜索客户
          url: https://www.linkedin.com/
        - name: Youtube 
          description: 全球最大的视频平台
          url: https://www.youtube.com/

    - name: 视频会议
      sites:
        - name: 微软Teams
          description: 微软打造的公司管理工具，国外用户量大，视频会议方便
          url: https://www.microsoft.com/zh-cn/microsoft-teams/group-chat-software/
        - name: Zoom
          description: 轻松会议，开启你的在家办公生活
          url: https://zoom.us/



    - name: 外贸收款
      sites:
        - name: 西联
          description: 最早进入中国的国际汇款服务之一
          url: https://www.westernunion.com/cn/zh/home.html

        - name: XTransfer
          description: 一站式外贸企业跨境金融和风控服务公司
          url: https://www.xtransfer.cn/

        - name: Paypal
          description: 全球通用第三方支付平台,为您的跨境交易提供保障
          url: https://www.paypal.com/
        - name: 派安盈
          description: Payoneer 派安盈为您开启全球跨境商贸的无限机会。
          url: https://www.payoneer.com.cn/
        - name: 连连支付
          description: 对接全球跨境电商平台，阶梯费率，提现实时到账，安全可靠，合规透明。
          url: https://www.lianlianpay.com/
    - name: 关键词工具
      sites:
        - name: Answer the Public
          description: 深度挖掘相关语义关键词以及客户问题
          url: https://answerthepublic.com/
        - name: Keywood Finder
          description: 发现低难度SEO长尾词
          url: https://keywordtool.io/
        - name: SEMRush
          description: 深度了解你和竞争对手的网站差距
          url: https://www.semrush.com/
        - name: Ahrefs
          description: 外链研究利器
          url: https://ahrefs.com
        - name: WordTracker
          description: 拓展关键词
          url: https://www.wordtracker.com/
        - name: 谷歌关键词规划师
          description: 谷歌官方付费推广关键词有规划方案
          url: https://www.google.com/adwords/

    - name: 客户搜索
      sites:
        - name: 全社交平台客户搜索
          description: 通过姓名，电话，地址，邮箱查找客户在社交平台上的信息
          url: https://www.spokeo.com/
        - name: 自定义谷歌搜索
          description: 定制化搜索结果
          url: https://www.wideindex.com/
        - name: 网站时光机
          description: 穿越时光，查找网站的历史记录
          url: https://web.archive.org/


    - name: 谷歌浏览器插件
      sites:
        - name: Grammarly 语法纠正
          description: 自动纠错，发现文本中的语句错误，及时提醒
          url: https://chrome.google.com/webstore/detail/grammarly-for-chrome/kbfnbcaeplbcioakkpcpgfkobkghlhen
        - name: Hunter.io
          description: 客户邮箱发现工具
          url: https://chrome.google.com/webstore/detail/hunter-email-finder-exten/hgmhmanijnjhaffoampdlllchpolkdnj
        - name: Similar Web
          description: 相似网站查询，同类客户网站搜索
          url: https://chrome.google.com/webstore/detail/similarweb-traffic-rank-w/hoklmmgfnpapgjgcpechhaamimifchmp
        - name: Wappalyzer 
          description: 独立站技术研究，分析目标网站的属性
          url: https://chrome.google.com/webstore/detail/wappalyzer-technology-pro/gppongmhjkpfnbhagpmjfkannfbllamg
    
    - name: 招聘 & 求职
      sites:
        - name: 大众人才网 - 高校网络双选会
          description: 高效线上就业工作双选会企业报名入口
          url: https://www.dazhonghr.com/jobfair/main
          
        - name: 求职&工作信息发布邮箱 jobs@weqihang.cn
          description: 发布企业人才需求 & 优质人才推荐，为人才和企业搭桥铺路
          url: https://jobs@weqihang.cn


    - name: 内容工具
      sites:
        - name: Answer the Public
          description: 根据5W1H（What/Who/When/Where/Why/How）产生出以关键词为核心的内容拓展方向。
          url: https://answerthepublic.com/
        - name: Buzzsumo
          description: 根据社媒分享查找当前最热、最流行的内容，掌握内容生产利器。
          url: https://app.buzzsumo.com/
        - name: AllTop
          description: 新闻内容聚合网站，快速了解当前大事向。
          url: https://alltop.com/
        - name: HubSpot 话题生成器
          description: 输入关键词，生成你的博客标题，再也不怕文思枯竭了！
          url: https://www.hubspot.com/blog-topic-generator


    - name: 外贸论坛
      sites:
        - name: 米课圈
          description: 最活跃的外贸社区。
          url: https://ask.imiker.com/
        - name: 福步外贸
          description: 中国最大的专业外贸论坛，致力于打造全球最具人气、最实用的外贸社区。
          url: https://bbs.fobshanghai.com/
        - name: 雨果网
          description: 致力于为跨境电商从业者提供全球产业出海，链接全球流通，实现全球品牌的产业互联网平台。
          url: https://www.cifnews.com/
        - name: 顾小北博客
          description: 跨境干货，营销知识分享。
          url: https://www.guxiaobei.com/
